### ISSUE TITLE
ERROR in Error: Metadata version mismatch for module /home/ajinesh/rigor/nera-frontend/node_modules/ngx-pagination-bootstrap/dist/index.d.ts, found version 4, expected 3,

### ISSUE THREAD

**Issue by ajmeersha** [manishjanky/ngx-pagination-bootstrap#2]
its not supported for angular version 4

**Comment by manishjanky** [comment]
Can you please share the version of angular you are using. i.e all angular modules you have in you package.json

**Comment by ajmeersha** [comment]
"@angular/animations": "^4.2.4",
    "@angular/common": "^4.2.4",
    "@angular/compiler": "^4.2.4",
    "@angular/core": "^4.2.4",
    "@angular/forms": "^4.2.4",
    "@angular/http": "^4.2.4",
    "@angular/platform-browser": "^4.2.4",
    "@angular/platform-browser-dynamic": "^4.2.4",
    "@angular/router": "^4.2.4",
    "@types/jqueryui": "^1.11.35",
    "angular-calendar": "^0.21.3",
    "angular-datatables": "^4.4.1",
    "angular-dual-listbox": "^4.4.0",
    "angular-froala-wysiwyg": "^2.6.6",
    "angular2-jwt": "^0.2.3",
    "angular2-moment": "^1.8.0",
    "babel-regenerator-runtime": "^6.5.0",
    "bootstrap": "^4.0.0-alpha.6",
    "bootstrap-datepicker": "^1.7.1",
    "bootstrap-timepicker": "^0.5.2",
    "chart.js": "^2.7.1",
    "core-js": "^2.4.1",
    "datatables.net": "^1.10.16",
    "datatables.net-bs": "^1.10.16",
    "datatables.net-bs4": "^1.10.16",
    "datatables.net-buttons": "^1.4.2",
    "datatables.net-buttons-dt": "^1.4.2",
    "datatables.net-dt": "^1.10.16",
    "font-awesome": "^4.7.0",
    "jquery": "^3.2.1",
    "jquery-ui-sortable": "^1.0.0",
    "jquery.filer": "^1.3.0",
    "jqueryui": "^1.11.1",
    "jszip": "^3.1.5",
    "lodash": "^4.17.4",
    "moment": "^2.20.1",
    "ng-pick-datetime": "4.3.4",
    "ng2-alt-summernote": "^2.0.0",
    "ng2-charts": "^1.6.0",
    "ng2-file-upload": "^1.3.0",
    "ng2-slim-loading-bar": "^4.0.0",
    "ng2-toastr": "^4.1.2",
    "ngx-slimscroll": "^3.4.1",
    "pdfmake": "^0.1.34",
    "rxjs": "^5.4.2",
    "summernote": "^0.8.8",
    "sweetalert2": "^7.9.2",
    "toastr-ng2": "^4.1.1",
    "zone.js": "^0.8.14"

**Comment by manishjanky** [comment]
Thanks. Let me have a look into this. Will update you soon :)

**Comment by ajmeersha** [comment]
kk by the way the plugin is awesome and make sure to work with angular 4 also,, that ll be great

**Comment by manishjanky** [comment]
Thanks for your appreciation :).

This issue seems to be due to angular version mismatch. Please try updating angular version to latest version.
execute `npm update` and then try it should work. 

And also i will try and look into the issue and would make it work for all versions above `v4.0.0 `.
Let me know if you still face issues.

**Comment by ajmeersha** [comment]
i am using angular 4 only.... can u make it work for angular 4 will be very useful for me

**Comment by manishjanky** [comment]
ok will update you soon.

**Comment by manishjanky** [comment]
@ajmeersha actually this plugin is compiled with Angular 5. So only this error is popping up. As from th discussion here 
https://github.com/angular/angular/issues/19607

I got to know that there is no backward compatibility. 

So in order to solve this you can update your angular version. As it wont have any breaking changes because whatever is built in angular 4 is compatible with Angular 5. But not vice versa.

So please update your angular version to 5 and things will work fine.

**Comment by manishjanky** [comment]
@ajmeersha  have fixed the issue. Will publish the updated version.
Now the plugin will work with `v4.0.0` and above
Tested with `v4.0.0` and `v5.2.0`

Will close the issue once published

Thanks for bringing this issue up. :)
